#!/bin/sh

#get host files
wget -O/tmp/mvps.hosts "http://winhelp2002.mvps.org/hosts.txt"
wget -O/tmp/yoyo.hosts "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=&mimetype=plaintext"
wget -O/tmp/malw.hosts "http://www.malwaredomainlist.com/hostslist/hosts.txt"

echo "#autogenerated hosts file. put permanent host definitions in /etc/hosts.orig" > /tmp/new.hosts

#cat all files, unique hosts only
cat /tmp/mvps.hosts | grep -v "#" | sort | uniq >> /tmp/new.hosts
cat /tmp/yoyo.hosts | grep -v "#" | sort | uniq >> /tmp/new.hosts
cat /tmp/malw.hosts | grep -v "#" | sort | uniq >> /tmp/new.hosts

#also add the local hostfile (this has to be created before using
#this script
cat /etc/hosts.orig >> /tmp/new.hosts

#save concatenated lists to local hosts file
mv /tmp/new.hosts /etc/hosts

echo updated ad- and malware hosts
